# Generated by Django 6.1.1 on 2026-09-20 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('etiquetas', models.CharField(blank=True, help_text='Separe por vírgulas. Ex.: arquitetura, imagem, render', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('teste', 'Em teste'), ('feita', 'Feita')], default='rascunho', max_length=10)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'ideia',
                'verbose_name_plural': 'ideias',
                'ordering': ['-atualizado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('etiquetas', models.CharField(blank=True, help_text='Separe por vírgulas. Ex.: arquitetura, imagem, render', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('url', models.URLField(max_length=500, verbose_name='endereço (URL)')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
                'ordering': ['-atualizado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('etiquetas', models.CharField(blank=True, help_text='Separe por vírgulas. Ex.: arquitetura, imagem, render', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('texto', models.TextField(verbose_name='texto do prompt')),
                ('ferramenta', models.CharField(blank=True, help_text='Ex.: Claude, Midjourney, ChatGPT', max_length=100, verbose_name='ferramenta / modelo')),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('favorito', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'prompt',
                'verbose_name_plural': 'prompts',
                'ordering': ['-atualizado_em'],
                'abstract': False,
            },
        ),
    ]
