# Generated by Django 6.1.1 on 2026-09-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='descricao',
            field=models.TextField(blank=True, help_text='Para que serve este prompt? É isto que aparece no card.', verbose_name='descrição'),
        ),
    ]
