# Generated by Django 5.2.17 on 2026-09-22 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acervo", "0003_perfil"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                (
                    "etiquetas",
                    models.CharField(
                        blank=True,
                        help_text="Separe por vírgulas. Ex.: arquitetura, imagem, render",
                        max_length=200,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "url",
                    models.URLField(max_length=500, verbose_name="endereço do vídeo"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "resumo",
                    models.TextField(
                        blank=True,
                        help_text="Um resumo do conteúdo do vídeo, para lembrar do que se trata sem assistir de novo.",
                        verbose_name="resumo",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "vídeo",
                "verbose_name_plural": "vídeos",
                "ordering": ["-atualizado_em"],
                "abstract": False,
            },
        ),
    ]
